#include "./structure.hpp"
#include "./point.hpp"
#include "./push.hpp"
#include "./concatenate.hpp"
#include "./vertex.hpp"
#include "./star.hpp"
#include "./facet.hpp"
#include "./closure.hpp"
#include "./skeleton.hpp"
#include "./link.hpp"
#include "./simplex/simplex.hpp"
#include "./intersect.hpp"

// Dependent from ::linear::vector::distance
#include "./vector/vector.hpp"
#include "./property/property.hpp"
