#include "./average.hpp"
#include "./count.hpp"
#include "./maximum.hpp"
#include "./minimum.hpp"
#include "./summae.hpp"

#include "./gaussV.hpp"
#include "./gaussV1.hpp"
#include "./gaussV2.hpp"
#include "./gaussV3.hpp"
#include "./interval.hpp"
#include "./skewness.hpp"
#include "./histogram.hpp"
