#include "./clamper.hpp"
#include "./pdf.hpp"
#include "./convex.hpp"
#include "./gabor.hpp"
#include "./bais.hpp"
#include "./gain.hpp"
#include "./binomial.hpp"
#include "./factorial.hpp"
#include "./gcd.hpp"
#include "./lcm.hpp"
#include "./power.hpp"
#include "./signum.hpp"
#include "./ricker.hpp"
#include "./combinations.hpp"
#include "./sigmoid.hpp"

#include "./sfc/sfc.hpp"
#include "./distribution/distribution.hpp"