#include "./area.hpp"
#include "./structure.hpp"
#include "./inside.hpp"
#include "./centroid.hpp"
#include "./circumradius.hpp"
#include "./inradius.hpp"
#include "./barycentric.hpp"
#include "./angle.hpp"
#include "./height.hpp"
#include "./valid.hpp"

#include "./circumcenter.hpp"
#include "./orthocenter.hpp"
