#cmake_minimum_required(VERSION 2.8)

add_executable(  Math_Plynomial_Cubic_Evaluate             evaluate.cpp )
add_executable(  Math_Plynomial_Cubic_Solve                   solve.cpp solve-cardano.cpp solve-viete.cpp solve-brian.cpp )
add_executable(  Math_Plynomial_Cubic_Interpolate       interpolate.cpp )
add_executable(  Math_Plynomial_Cubic_Construct           construct.cpp )
add_executable(  Math_Plynomial_Cubic_Depressed           depressed.cpp )


