#include "./evaluate.hpp"
#include "./normalize.hpp"
#include "./structure.hpp"
#include "./optimize.hpp"
#include "./monicize.hpp"

#include "./cubic/cubic.hpp"
#include "./linear/linear.hpp"
#include "./quadric/quadric.hpp"
#include "./quartic/quartic.hpp"